export default[
    {
        id:1,
        sr:"../imgs/watch.jpg" ,
        heading:"MEGALITH Mens Watches Chronograph Waterproof Watch",
        rating:"4.5",
        review:"8267",
        country:"INDIA",
        rate:"$987",
        open:0,
        location:"online",

    },
    {
        id:2,
        sr:"../imgs/watch2.jpeg" ,
        heading:"Curren 50mm Big Dial Watches Men Luxury Brand Unique Sport Wristwatch Men ",
        rating:"4.6",
        review:"2267",
        country:"UAE",
        rate:"$869",
        open:4,
        location:"offline",
    },
    {
        id:3,
        sr:"../imgs/watch3.jpg", 
        heading:"Luxury Male Elegant Ultra Thin Watch Men Business Stainless Steel Mesh Quartz ",
        rating:"4.1",
        review:"5267",
        country:"USA",
        rate:"$690",
        open:7,
        location:"online",
    },
    {
        id:4,
        sr:"../imgs/watch4.jpg" ,
        heading:"China Kademan Vogue Leather Strap Quartz ",
        rating:"4.4",
        review:"4267",
        country:"CHINA",
        rate:"$893",
        open:0,
        location:"online",

    },
    {
        id:5,
        sr:"../imgs/watch.jpg" ,
        heading:"MEGALITH Mens Watches Chronograph Waterproof Watch",
        rating:"4.5",
        review:"8267",
        country:"INDIA",
        rate:"$987",
        open:6,
        location:"offline",

    },
]